title: "AK // INFRASTRUCTURE LOG"
author:
  name: "Anthony Klein"
  email: github@aklein.pro
  github: KDN-Cloud

description: >
  A centralized repository for technical documentation, systems administration 
  workflows, and infrastructure engineering insights.

url: https://b.aklein.me
repository: "KDN-Cloud/b.aklein.me"

theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social:
  type: Decentralized Social Network
  name: AK
  links: https://aklein.pro

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
